### ISSUE TITLE
Recieving gate is inactive

### ISSUE THREAD

**Issue by Sarous** [PC-Logix/LanteaCraft#258]
Occasionally, when you dial a gate; it does not matter if it is the same dimension or different, the receiving gate does not flag as an in-use gate, neither does it have the wormhole animation. The receiving gate can immediately dial out, but the original gate cannot be dialed back to until its wormhole closes.

**Comment by Zunth5** [comment]
Is it possible to add a config option for continuous "spot loading" of chunks known to contain stargates? This could be useful in some cases where servers have the extra ability to pick up the processing for those chunks. Although this would likely have to be removed once spawning pyramid/stargates got added to the mod again.

**Comment by AfterLifeLochie** [comment]
@Zunth5 Not really. I removed that feature particularly because people were complaining about how Stargates had to load a 3x3 chunk area around them (because they were being abused as 'free' chunk loaders). 

@morlanius An iris setup is already planned. It behaves similar to that of the series. The OC/CC integration will be changed as well.

**Comment by AfterLifeLochie** [comment]
This behavioural issue should be resolved as of `LC2-5`.
