### ISSUE TITLE
.getActiveCheverons 

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#277]
This has almost no use accept for astatic in the cc dialing menu but it would be a nice feature

**Comment by dominikh** [comment]
There's already several events (sgIncoming, sgChevronEncode) that tell you which chevrons are active and set to what symbol. Listen to the events and build a correct internal representation of the gate's state.

**Comment by AfterLifeLochie** [comment]
You can do this by just listening to the events. We already tell you how and which chevrons are being encoded essentially, you just have to wait for the states.

I also don't want to add things like that because I don't want to make it *easy* to use OC and CC. It's meant to be a challenge to use most of the mod, so I feel this would defeat the purpose of having the events and balancing in the first place.
