### ISSUE TITLE
Chevrons not lighting up when dialing on DHD

### ISSUE THREAD

**Issue by hehe3301** [PC-Logix/LanteaCraft#285]
Chevrons not lighting up when dialing addresses on the DHD

**Comment by MichiyoRavencroft** [comment]
I just tested, and chevrons do indeed light up when entering the address on the DHD and hitting the center button.  If you mean they don't light up in real time as you enter the address they are not supposed to, the dialing process can not start until the entire address is entered because we have to try to load the remote chunk, and the full address is required to find the remote gate.

**Comment by hehe3301** [comment]
I ment on the DHD that does not light up

**Comment by MichiyoRavencroft** [comment]
Do you mean like the symbols on the DHD lighting up as you enter them?

**Comment by hehe3301** [comment]
Yes those

**Comment by MichiyoRavencroft** [comment]
That's not a feature we are currently interested in adding.
