### ISSUE TITLE
some more computercraft functions/events and a other thing

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#349]
you probably had planned some of these already but I just want to make shure and mabye add some more 

the getActivatedGlhyps always returns nil but you probably know that

isConnected/isOpen so you  can make the diference between just 9 locked chevrons and a connected gate

deactivateAllChevrons a way to deactivate all the chevron at once (someting like #332 but for cc)
edit:(I mean really at once not one by one)
 
iscomplete this is the same as the old LC just to check if the gate is complete

getAddress also from the old LC

getConnectedAddress before you would have to do with events but if a pc startsup afther the gate openend it doesnt know with what address its connected 

for when more type of gates are added 
getGateType 

events 
most of it is discust in #272 
but you say there will be no event trown when a player is killed by the iris maybe a event like that to 
just to see if someone tried to enter

the other thing
when you see a stargate that is controlled by a computer and you place a dhd you have "full" control of the gate it would be nice to have a way to disable this 
the problem is in "real life" the gate would probably still listen to the dhd so that would make it non cannon 

if I copied some things form other post's that wasn't my intension I try to look if things already exist but its hard somtimes.

**Comment by AfterLifeLochie** [comment]
Not all of these features will be added - because I deliberately want it to be difficult. I'll have a think and get back to it.

**Comment by AfterLifeLochie** [comment]
> the getActivatedGlhyps always returns nil but you probably know that

This should now be fixed.

> isConnected/isOpen so you can make the diference between just 9 locked chevrons and a connected gate

You only get fired a `connect` event if dialling is successful, so just listen for that. If it's not a success, you immediately get a `disconnect` even instead.

> deactivateAllChevrons a way to deactivate all the chevron at once

I am considering this, but you can just check the activated glyphs and queue an unlock for the Stargate. Remember, Stargate commands aren't blocking - your code will continue, even if you tell the Stargate to do a lot of things (which take time!).

> iscomplete this is the same as the old LC just to check if the gate is complete

I have added this, use `isValid`; it'll return `true` or `false` if the Stargate is formed or not.

> getConnectedAddress before you would have to do with events but if a pc startsup afther the gate openend it doesnt know with what address its connected

This is part of the point - the Stargate doesn't hand out this information to just anyone. If you're not there to observe the device which is dialling the Stargate, you won't (and can't) know the connected address.

> getGateType

I have added this, it's `getStargateType`.

> but you say there will be no event trown when a player is killed by the iris maybe a event like that to 

I do recall saying this, but I'm not sure whether I'm going to continue with that attitude - I might think about having some way of notifying computers/etc when things like "impact with iris" happens, but I'm still opposed to telling you what has impacted (because they never really re-form).

**Comment by lieven121** [comment]
the getStargateType gives me a nill and nice work 

thx for the present and happy holidays

**Comment by AfterLifeLochie** [comment]
Internally, getStargateType returns an Enumeration, so I guess I never wrote handling to convert Enumeration to a String name. Will fix later.

**Comment by AfterLifeLochie** [comment]
The issue with `getStargateType` returning null should now be fixed as of 87ebb3ab5075114d1106a8841aee11c4f1d3377d.
