### ISSUE TITLE
Which version should I use?

### ISSUE THREAD

**Issue by Ionaru** [PC-Logix/LanteaCraft#383]
Hello,

In my modpack, I've been running LC1-1.7.10-70 for a while now and it's working decently. I've been wondering if now is the time to update to LC2-1.7.10-15, but I've been seeing a lot of issues opened for that version on Github and the download is still in the "unstable" section of the website.
However in issue #379 you mentioned LC2-1.7.10-15 to be more stable.

So should I consider upgrading the mod to LC2-1.7.10-15 or keep running LC1-1.7.10-70 for the moment?

**Comment by joneschrisan** [comment]
I think the 2 versions are not compatible with each other. Someone will correct me if I'm wrong though.

**Comment by Ionaru** [comment]
They aren't, I am aware that all LanteaCraft items and blocks currently in my world will vanish.

**Comment by joneschrisan** [comment]
Then I would say it's a matter of preference, do you want what you aready have to keep working as it is, or do you want to be able to use the new features that are planned for up comming releases and any bug fixes / improvements that have been done already?

**Comment by Zunth5** [comment]
I beleive one of the only playable drawbacks of 1.7.10-70 is the chunkloading issue where a origin gate could remain phantom connected once the dialed gate is closed (or the connection is broken once traveling through the dialed gate) and the gates deforming back into blocks. I fix both of these with chunk loaders for the time being.

LC2 seems to address these in a steller way and has the boon of having all the features coming down the line. I was holding out for more releases so that I could start a better ftb server with friends, but the lack of progress made me stick with the old version because its moreover what I consider to be playable. 

Dont get me wrong; I think LC2 will be really kick butt once its brought back in the basics from LC(1) and it feels playable again.

**Comment by AfterLifeLochie** [comment]
Firstly - this sort of question should not be asked on the issue tracker; issue trackers are for bugs and suggestions, not for questions or queries. You should direct your queries to the [MCF thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292427-lanteacraft) where possible. If you're not sure if you should open or use an issue, use the [can I issue?](http://afterlifelochie.net/can-i-issue/) tool.

> I've been seeing a lot of issues opened for that version on Github and the download is still in the "unstable" section of the website

LC-1.7.10-15 is relatively stable at this stage - there's nothing seriously crashy having been reported to me; it's mostly just minor issues and tweaks. Generally speaking, if a release comes out and it's not stable, I'll immediately patch the crash bugs.

The unstable section is there because initially these builds were going to be absolutely bleeding edge, and then promoted when they were stable. I haven't really promoted any builds to a mainstream page just yet, because I'm still aiming for feature-parity.

> They aren't, I am aware that all LanteaCraft items and blocks currently in my world will vanish.

This is true, though I am considering changing the mod-ID so that you can keep both running concurrently, and then upgrade them somehow.

> I was holding out for more releases so that I could start a better ftb server with friends, but the lack of progress made me stick with the old version because its moreover what I consider to be playable.

This is partially because most of my "development time" now goes to my job; Minecraft doesn't really make me any money (and it shouldn't), so I have to support myself with full-time employment. Modding is going to have to take a side-seat for a while, at least until I can get le real-life sorted out. There will still be progress going forwards, but it's just hard to find time currently.

Essentially, this boils down to the following: you  should upgrade only if:
* You're okay with losing your progress
* You're okay with losing some popular(?) features
* You want or need key bug fixes (like chunk loading, etc)
* You're okay with making sure your pack is updated regularly, because once I get a chance to do development again, there will be lots and lots of builds.

**Comment by AfterLifeLochie** [comment]
I'm assuming this answers your question.
