### ISSUE TITLE
Config doesnt update and doesnt regenerate all the options

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#420]
### Submission checklist
- [x] Check that you are running the latest recommended version of LanteaCraft.
  I read something in the past about textures but couldn't find it so ...
- [ x ] Check that the issue isn't a known problem already (https://github.com/PC-Logix/LanteaCraft/issues).
- [x] Check that you can repeat this issue with just LanteaCraft installed.
### Expected behavior

when installing a new version the config's should update

and all options should generate when deleting old config 
### Actual behavior

the config file hasn't updated since v 15
and when I delete it the option for texture quality isn't generated (even it does work look at picture)

and what is version 1.0 because that never updates either
### Steps to reproduce

install a older version of ex: LC  2-20
install a new version ex LC 21
look at the configs
### System information
- MinecraftForge version: _10.13.4.1614_
- LanteaCraft version: _21_

![image](https://cloud.githubusercontent.com/assets/7773244/13903895/386218d0-ee8d-11e5-98de-9a35580d1fef.png)
t

**Comment by AfterLifeLochie** [comment]
> when deleting old config

LanteaCraft doesn't delete the old config, it rewrites updated configuration if (and when) new configuration options are added.

> the config's should update

Only if new configuration is required.

> and when I delete it the option for texture quality isn't generated

Because the code currently does not check the rendering preferences, but this will be added.

> what is version 1.0 because that never updates

This is the version of the XML specification, not a LanteaCraft number. It should always be just `1.0`.

Essentially the only problem here is that the configuration isn't being observed.

**Comment by lieven121** [comment]
so the "last written" is on what version it was updated to a new config? that would make sense thx

and if you look at the picture it does check rendering preferences it just doesn't generate them in config if you place them in manually they work just fine
(please don't remove it for now I love the 128 gate)
