### ISSUE TITLE
Crash on placing doors

### ISSUE THREAD

**Issue by Cronosus** [PC-Logix/LanteaCraft#437]
### Submission checklist
- [x] Check that you are running the latest recommended version of LanteaCraft.
- [x] Check that the issue isn't a known problem already (https://github.com/PC-Logix/LanteaCraft/issues).
- [x] Check that you can repeat this issue with just LanteaCraft installed.
### Steps to reproduce

happened always, and you can use same type of door (only lantean or only goauld or both)
minimum required doors: 4

![01](https://cloud.githubusercontent.com/assets/5349950/14962342/aa71ce74-109e-11e6-98b0-1c67b2f22483.png)
![02](https://cloud.githubusercontent.com/assets/5349950/14962343/aa7835b6-109e-11e6-97e6-9c54685a67af.png)
![03](https://cloud.githubusercontent.com/assets/5349950/14962344/aa852546-109e-11e6-9c0b-661976633f53.png)
### System information
- MinecraftForge version: 10.13.4.1614
- LanteaCraft version: LanteaCraft-1.7.10-21
- Logs: 
- \- Crash report: http://cronos.wz.cz/mc/lc/crash-2016-05-02_19.40.17-server.txt
- \- Log: http://cronos.wz.cz/mc/lc/beforecrash-latest.log

**Comment by AfterLifeLochie** [comment]
Despite the lack of logs I've figured out what this is caused by. Please, make sure you include the F3 Debug view in your screenshots so I can see what your coordinates and your facing angle is, since this can only be reproduced if you stand and place in a certain way.  🎱

**Comment by Cronosus** [comment]
caused anywhere in world
easy steps.. to reproduce, just place two doors, leave on free block, place another door, and then place door to this free space between doors
http://cronos.wz.cz/mc/cr-lc.txt
edit: ok, tested again with b22, i must face to South

**Comment by AfterLifeLochie** [comment]
I've changed the door mechanics so that the following now happens:
- Door blocks place only 1x Door panel, rather than the 2 high model
- Door blocks can be placed on top of each other by crouching to avoid activation
- If you want to switch from the "large squares" to the smaller more door-looking texture, break and replace the door panels you want to update. The second texture only appears if there is a door above the block being placed.
- Doors will no longer crash if you try to merge two networks of opposing placement direction.
