### ISSUE TITLE
LC2-22: Request true/false return for CC iris calls

### ISSUE THREAD

**Issue by HydrantHunter** [PC-Logix/LanteaCraft#448]
### Submission checklist

- [X] Check that you are running the latest recommended version of LanteaCraft.
- [X] Check that the issue isn't a known problem already (https://github.com/PC-Logix/LanteaCraft/issues).
- [ ] Check that you can repeat this issue with just LanteaCraft installed.  NOTE: ComputerCraft also required.

### Expected behavior

Calling openIris() or closeIris() returns true or false depending on whether the action is started

### Actual behavior

Calling openIris() or closeIris() returns nothing, making it difficult to determine if the action is taking place or not.

### Steps to reproduce

In the CC Lua console wrap a stargate (with iris installed) and open or close the iris

### System information

- MinecraftForge version: 10.13.4.1558
- LanteaCraft version: LC2-22
- Logs: no logs

**Comment by AfterLifeLochie** [comment]
Just hook the events that are passed to the system? There should be four of them in total, representing each state transition. 

This happens because Stargates are entirely asynchronous; it isn't possible for us to tell immediately if a Stargate action will complete. This also allows multiple players, command sources and systems to interact with a Stargate simultaneously, unlike previous versions.

**Comment by HydrantHunter** [comment]
Ahh, OK - I can work with it - thanks for the clarification :)
